services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - ./migrations:/migrations
    depends_on:
      - db 
  
  db:
    image: postgres:15.3-alpine3.18
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=urls
    volumes: 
      - ./db:/var/lib/postgresql/data
